### PR TITLE
attempt adding support for scanners with adf

### PR DESCRIPTION
**Pull request by kn100**
I'm really not sure what I'm doing with ADF scanners, but this is an attempt to add support for them. You can build and run the code yourself, or grab the zip file below which contains prebuilt binaries for arm64, arm6, 386, or amd64 systems. If these builds work for your scanner, let me know and I'll get this merged in. 

[telescan.zip](https://github.com/kn100/telescan/files/11473710/telescan.zip)

### CODE REVIEW

**Comment by stnokott** [comment]
Needed to make a few changes to make this work, one of them leaving me very confused:

- `InputSource` needs to be "Feeder" (in my case at least), otherwise I get a HTTP 409
- TLS needs to be configured to not validate SSL connections. Like so:
```go
cl := airscan.NewClientForService(s.DNSSDBrowseEntry)
transport := cl.HTTPClient.(*http.Client).Transport.(*http.Transport)
transport.TLSClientConfig = &tls.Config{InsecureSkipVerify: true}
```
I know that this change is not included in my PR #12, but I swear it was working without it before (now it doesn't anymore).

Maybe I missed something in my earlier attempts at figuring airscan out, but now I can't get it to work without that TLS change...

Would be interesting if other scanners work with that option, then it might be worth having it enabled by default.

**Comment by kn100** [comment]
> Needed to make a few changes to make this work, one of them leaving me very confused:
> 
> * `InputSource` needs to be "Feeder" (in my case at least), otherwise I get a HTTP 409
> * TLS needs to be configured to not validate SSL connections. Like so:
> 
> ```go
> cl := airscan.NewClientForService(s.DNSSDBrowseEntry)
> transport := cl.HTTPClient.(*http.Client).Transport.(*http.Transport)
> transport.TLSClientConfig = &tls.Config{InsecureSkipVerify: true}
> ```
> 
> I know that this change is not included in my PR #12, but I swear it was working without it before (now it doesn't anymore).
> 
> Maybe I missed something in my earlier attempts at figuring airscan out, but now I can't get it to work without that TLS change...
> 
> Would be interesting if other scanners work with that option, then it might be worth having it enabled by default.

Give me a day or so, I'll amend this PR based on what you said and if you'd be so kind as to test it a second time? It's such a pain not having a scanner of this type available to test with!

**Comment by kn100** [comment]
The good news is the skipping of verification of TLS certificates does not break use with my scanner. I've also made the other change you suggested here. I'm going to merge this for now, since I can't imagine it making things any worse. Could you test and let me know if it works for you now?

**Comment by stnokott** [comment]
Can confirm 602dc89a84ebae45b1883809d0d1a4c3465242ac works out of the box now.

**Pull request merged**
